"""Deriving herdr's chrome palette from a theme's ANSI palette.

herdr paints its sidebar and tab bar on its own surfaces, not on the terminal
background. Left to inherit, it picks combinations nothing has checked - which
is how a selected workspace row ends up with a subtitle at 2.5:1 against its
own highlight.

Deriving the block explicitly puts every one of those pairings under the same
contrast floor as the rest of the theme.
"""

from __future__ import annotations

from .color import (
    CONTRAST_TARGET,
    contrast,
    from_hls,
    luminance,
    remediate_against,
    to_hls,
)


def _shift(color: str, amount: float) -> str:
    """Move a colour away from itself in lightness, direction set by darkness."""
    hue, light, sat = to_hls(color)
    step = amount if luminance(color) < 0.5 else -amount
    return from_hls(hue, max(0.0, min(1.0, light + step)), sat)


def herdr_custom(palette: dict, background: str, foreground: str) -> str:
    """Build a `[theme.custom]` block whose every text token is legible on
    every surface herdr draws it on."""
    # Surfaces are derived rather than taken from palette slot 0: on most
    # themes slot 0 is near-identical to the background, which gives a
    # selection highlight nothing can be read against.
    surface0 = _shift(background, 0.06)
    surface1 = _shift(background, 0.14)
    surfaces = [background, surface0, surface1]

    def fix(color: str, target: float = CONTRAST_TARGET) -> str:
        return remediate_against(color, surfaces, target)

    def slot(index: int, fallback: str) -> str:
        return palette.get(index, fallback)

    tokens = {
        # Primary label - the workspace name. Held to the stricter floor.
        "text": fix(foreground, 7.0),
        # The subtitle line under it. This is the one that was failing.
        "subtext0": fix(slot(7, foreground)),
        "overlay0": fix(slot(8, foreground)),
        "overlay1": fix(slot(12, slot(4, foreground))),
        "surface0": surface0,
        "surface1": surface1,
        "accent": fix(slot(3, slot(11, foreground))),
        "blue": fix(slot(4, foreground)),
        "green": fix(slot(2, foreground)),
        "yellow": fix(slot(3, foreground)),
        "red": fix(slot(1, foreground)),
        "teal": fix(slot(6, foreground)),
        "mauve": fix(slot(5, foreground)),
        "peach": fix(slot(11, slot(3, foreground))),
    }

    # The header comes first and the comments sit inside the table: the block is
    # stripped from `[theme.custom]` to the next section on every switch, so
    # anything written above that header would survive and accumulate.
    lines = [
        "[theme.custom]",
        "# Generated by `theme` - do not edit, it is rewritten on every switch.",
        "# Every text token below is corrected against the sidebar's own",
        f"# surfaces, so a selected row stays legible at {CONTRAST_TARGET}:1.",
    ]
    lines += [f'{k} = "{v}"' for k, v in tokens.items()]
    return "\n".join(lines) + "\n"


def check(palette: dict, background: str, foreground: str) -> list[tuple[str, float]]:
    """Report every text token against the worst surface it lands on."""
    block = herdr_custom(palette, background, foreground)
    values = dict(
        line.split(" = ")[0:2] for line in block.splitlines() if " = " in line
    )
    values = {k: v.strip('"') for k, v in values.items()}
    surfaces = [background, values["surface0"], values["surface1"]]
    out = []
    for token in ("text", "subtext0", "overlay0", "overlay1", "accent"):
        worst = min(contrast(values[token], s) for s in surfaces)
        out.append((token, worst))
    return out
