import type { CustomArgs, CustomOptions } from 'jsr:@ghostmind/run';
import { $ } from 'npm:zx@8';

// The CLI has no third-party dependencies, so "installing" is just putting an
// executable shim on PATH that points at the package in this repo. No venv, no
// build step, and edits to app/theme take effect immediately.
//
// The app path is resolved from this script's own location rather than from
// cwd or SRC: `run` executes scripts with an unpredictable working directory,
// and SRC is only set inside a devcontainer.
const APP = new URL('../app', import.meta.url).pathname.replace(/\/$/, '');

export default async function (_args: CustomArgs, opts: CustomOptions) {
  const { has } = opts;

  const dir = Deno.env.get('THEME_INSTALL_DIR') ??
    `${Deno.env.get('HOME')}/.local/bin`;
  const target = `${dir}/theme`;

  if (has('unlink')) {
    try {
      await Deno.remove(target);
      console.log(`removed ${target}`);
    } catch {
      console.log(`nothing at ${target}`);
    }
    return;
  }

  if (has('link')) {
    const python = Deno.env.get('THEME_PYTHON') ?? 'python3';
    const shim = [
      '#!/bin/sh',
      '# generated by `run routine install` - edits will be overwritten',
      `exec ${python} -c 'import sys; sys.path.insert(0, "${APP}"); from theme.cli import main; sys.exit(main())' "$@"`,
      '',
    ].join('\n');

    await Deno.mkdir(dir, { recursive: true });
    await Deno.writeTextFile(target, shim);
    await Deno.chmod(target, 0o755);

    console.log(`installed ${target}`);
    console.log(`  -> ${APP}/theme`);
    await $`${target} version`;
  }
}
