#!/usr/bin/env bash
# The CLI has no third-party dependencies, so "installing" is just putting an
# executable shim on PATH that points at the package in this repo. No venv, no
# build step, and edits to app/theme take effect immediately.
#
# The app path is resolved from this script's own location rather than from
# the working directory, so the routine works from anywhere.
#
# usage: scripts/install.sh link|unlink
set -euo pipefail

app="$(cd "$(dirname "$0")/../app" && pwd)"
dir="${THEME_INSTALL_DIR:-$HOME/.local/bin}"
target="$dir/theme"

case "${1:-}" in
  unlink)
    if [ -e "$target" ]; then
      rm "$target"
      echo "removed $target"
    else
      echo "nothing at $target"
    fi
    ;;
  link)
    python="${THEME_PYTHON:-python3}"
    mkdir -p "$dir"
    cat > "$target" <<SHIM
#!/bin/sh
# generated by \`run routine install\` - edits will be overwritten
exec $python -c 'import sys; sys.path.insert(0, "$app"); from theme.cli import main; sys.exit(main())' "\$@"
SHIM
    chmod 755 "$target"
    echo "installed $target"
    echo "  -> $app/theme"
    "$target" version
    ;;
  *)
    echo "usage: scripts/install.sh link|unlink" >&2
    exit 2
    ;;
esac
